package io.mosip.injivcrenderer.constants

object VcRendererErrorCodes {
    const val INVALID_RENDER_METHOD_TYPE = "ERR_INVALID_RENDER_METHOD_TYPE"
    const val INVALID_RENDER_SUITE = "ERR_INVALID_RENDER_SUITE"
    const val QR_CODE_GENERATION_FAILURE = "ERR_DURING_QR_CODE_GENERATION"

    const val MISSING_TEMPLATE_ID = "ERR_MISSING_TEMPLATE_ID"
    const val MISSING_JSON_PATH = "ERR_MISSING_JSON_PATH"
    const val SVG_FETCH_ERROR = "ERR_SVG_FETCH"
    const val INVALID_RENDER_METHOD = "ERR_INVALID_RENDER_METHOD"
    const val UNSUPPORTED_CREDENTIAL_FORMAT = "ERR_UNSUPPORTED_CREDENTIAL_FORMAT"
    const val MULTIBASE_VERIFICATION_FAILED = "ERR_MULTIBASE_VERIFICATION_FAILED"

}